package com.kpad.app.constant;

public class KpadConstant {

	public static String telegrafConfig = "[global_tags]\r\n"
			+ "        [agent]\r\n"
			+ "          interval = \"10s\"\r\n"
			+ "          round_interval = true\r\n"
			+ "          metric_batch_size = 1000\r\n"
			+ "          metric_buffer_limit = 10000\r\n"
			+ "          collection_jitter = \"0s\"\r\n"
			+ "          flush_interval = \"10s\"\r\n"
			+ "          flush_jitter = \"0s\"\r\n"
			+ "          precision = \"0s\"\r\n"
			+ "          hostname = \"\"\r\n"
			+ "          omit_hostname = false\r\n"
			+ "        [[inputs.cpu]]\r\n"
			+ "          percpu = true\r\n"
			+ "          totalcpu = true\r\n"
			+ "          collect_cpu_time = false\r\n"
			+ "          report_active = false\r\n"
			+ "          core_tags = false\r\n"
			+ "        [[inputs.disk]]\r\n"
			+ "          ignore_fs = [\"tmpfs\", \"devtmpfs\", \"devfs\", \"iso9660\", \"overlay\", \"aufs\", \"squashfs\"]\r\n"
			+ "        [[inputs.diskio]]\r\n"
			+ "        [[inputs.kernel]]\r\n"
			+ "        [[inputs.mem]]\r\n"
			+ "        [[inputs.processes]]\r\n"
			+ "          use_sudo = false\r\n"
			+ "        [[inputs.swap]]\r\n"
			+ "        [[inputs.system]]\r\n"
			+ "        [[outputs.influxdb_v2]]\r\n"
			+ "        urls = [\"http://localhost:8086\"]\r\n"
			+ "        token = \"SN9YAa02HRZ6oOz3qEwALlWUALldFw2kAGtfJkYtrjyuNR0wSpMJS8Sstds2MMWtahZDw0D59kohx0016tO5-A==\"\r\n"
			+ "        organization = \"TechQWare\"\r\n"
			+ "        bucket = \"Kpad\"\r\n";
	
	public static String urlConfig = "[[inputs.http_response]]\r\n"
			+ "  urls = [\"https://reebok.com\"]\r\n"
			+ "  follow_redirects = true\r\n"
			+ "  interval = \"20s\"\r\n"
			+ "  response_timeout = \"8s\"\r\n"
			+ "  collection_jitter = \"0s\"\r\n"
			+ "  collection_offset = \"0s\"\r\n"
			+ "  name_override = \"http_url_check\"\r\n"
			+ "  tags = {team = \"NSS\", bu = \"Commerce\"}\r\n"
			+ "\r\n"
			+ "[[inputs.http_response]]\r\n"
			+ "  urls = [\"https://puma.com\"]\r\n"
			+ "  follow_redirects = true\r\n"
			+ "  response_timeout = \"8s\"\r\n"
			+ "  interval = \"20s\"\r\n"
			+ "  collection_jitter = \"0s\"\r\n"
			+ "  collection_offset = \"0s\"\r\n"
			+ "  name_override = \"http_url_check\"\r\n"
			+ "  tags = {team = \"NSS\", bu = \"Commerce\"}\r\n"
			+ "\r\n"
			+ "[[inputs.http_response]]\r\n"
			+ "  urls = [\"https://nike.com\"]\r\n"
			+ "  follow_redirects = true\r\n"
			+ "  response_timeout = \"8s\"\r\n"
			+ "  interval = \"10s\"\r\n"
			+ "  collection_jitter = \"0s\"\r\n"
			+ "  collection_offset = \"0s\"\r\n"
			+ "  name_override = \"http_url_check\"\r\n"
			+ "  tags = {team = \"NSS\", bu = \"Commerce\"}\r\n"
			+ "\r\n"
			+ "[[inputs.http_response]]\r\n"
			+ "  urls = [\"https://amazon.com\"]\r\n"
			+ "  follow_redirects = true\r\n"
			+ "  response_timeout = \"8s\"\r\n"
			+ "  interval = \"10s\"\r\n"
			+ "  collection_jitter = \"0s\"\r\n"
			+ "  collection_offset = \"0s\"\r\n"
			+ "  name_override = \"http_url_check\"\r\n"
			+ "  tags = {team = \"NSS\", bu = \"Commerce\"}\r\n"
			+ "\r\n"
			+ "[[inputs.http_response]]\r\n"
			+ "  urls = [\"https://acko.com\"]\r\n"
			+ "  follow_redirects = true\r\n"
			+ "  response_timeout = \"8s\"\r\n"
			+ "  interval = \"10s\"\r\n"
			+ "  collection_jitter = \"0s\"\r\n"
			+ "  collection_offset = \"0s\"\r\n"
			+ "  name_override = \"http_url_check\"\r\n"
			+ "  tags = {team = \"NSS\", bu = \"Commerce\"}";
}
